### ISSUE TITLE
Place Block Structure Issues

### ISSUE THREAD

**Issue by NormanNormalington** [TinyModularThings/Scavenge#5]
I've been trying to setup shift right clicking with a particular item on a particular block to place a structure of about 38 blocks. I've used the scavenge error checking command, and it tells me there are no errors. However, when shift right clicking with said item on said block, only 9 blocks are placed, and then it just stops. I've been over my script a number of times without finding any glaring issues, but I'll post it here anyway - https://gist.github.com/NormanNormalington/3799182337f2e0d9f2401e3dd63a08d0

Something I did notice is that every time I try to place the structure, I get this error in the log file - https://gist.github.com/NormanNormalington/687de3d6e4a80ccedc2c131a6a45b199

Here's the full log file in case that helps - https://gist.github.com/NormanNormalington/147c504aef2d8462b9f83aeee9be984d

Edit: Using Scavenge V1.12-1.8.3.2 and Forge 14.23.5.2772

**Comment by Speiger** [comment]
ok this is an issue with scavenge not throwing errors if it can't find a block.
But the blocks that it is "not" placing are actually not found and it stored a bunch of "null Placement Tasks" which crash as soon it tries to place them.
which is the typo here: "name": "<astralsorcery:blockmarble",
I think the < is the issue here.

**Comment by NormanNormalington** [comment]
Works perfectly now, thanks. Sorry about that....

**Comment by Speiger** [comment]
No problem it was my fault for not throwing errors if a block couldnt be found.
Leaving this open as a TODO.
