### ISSUE TITLE
wiki help 1.16.5+

### ISSUE THREAD

**Issue by AlleCraft-alterego** [TinyModularThings/Scavenge#9]
i followed the new wiki, but it is slightly confusing and it does not say how to rename the scripts (i believe as you want) and i cannot get it to work, even copying and pasting the example scripts, isn't it better to give a sample datapack?

**Comment by Speiger** [comment]
@AlleCraft-alterego did you copy it into the right folder? If you use the datapack mod, did you install it there?
Also did you include a "datapack file"? Like you need that otherwise mc does not load them.

**Comment by AlleCraft-alterego** [comment]
i use openloader, it is not the first time I use openloader and it is not the first datapack I do for my modpacks

**Comment by Speiger** [comment]
Does scavenge dump the script or crash during loading.

**Comment by AlleCraft-alterego** [comment]
exemple in "scavenge_doc" folder ? (exist)

**Comment by Speiger** [comment]
Dumps are placed in the "resourcePacks" folder in the "minecraft" folder under the "scavenge_dumps" folder.
path: .minecraft/resourcepacks/scavenge_dumps
If you enable scavengedumps in the config. And if a script was loaded it will be dumped there every time the scripts get loaded.
(Its not a copy of the inputted script, but its a dump of the interpreted scripts so you actually see what it used and what got ignored)

Edit: Also can you show your script?

**Comment by AlleCraft-alterego** [comment]
scavenge_dumps  folder don't exist in my istance, and i have try script in your wiki after using my scripts (give kubejs existing item)

you don't have a discord server ? 

[Custom Sky.zip](https://github.com/TinyModularThings/Scavenge/files/6708753/Custom.Sky.zip)
[custom_things.zip](https://github.com/TinyModularThings/Scavenge/files/6708760/custom_things.zip)
you need put kubejs script in startup_scripts

**Comment by Speiger** [comment]
@AlleCraft-alterego yeah you messed up. "scavenge_scripts" not "scavenge_script" and i checked the tutorial. It even states "scavenge_scripts"

No wonder scavenge can not find these.

**Comment by AlleCraft-alterego** [comment]
lol sorry, i missed this "s" in my copy-paste...   first exemple script work but second exemple script for this: 

java.util.concurrent.CompletionException: com.google.gson.JsonParseException: Tag [count] couldn't be found in JsonObject: {"property":"scavenge_world:spawn_particles","particle":"minecraft:crit","count":3}

you have a discord server ?

**Comment by Speiger** [comment]
https://discord.gg/JD7M33A
One time use. Its a private discord Server

**Comment by Speiger** [comment]
@AlleCraft-alterego there is also a timeout of 1 hour.

**Comment by Speiger** [comment]
To answer your question "count" is no longer a "integer" its a math operation now. I think i updated the tutorial if not then this is on me. 
Why was it changed to a "MathOperation" instead of a Integer?
Very simple the command throws exactly the amount of particles out you want to see. This way you can at the very least add some randomness into it.

The get or crash function i added should have stated "expected a Object that couldn't be found" though docs with "spawn_particles" should be up to date.

**Comment by Speiger** [comment]
Yep the wiki is not correct.
Why it was incorrect? I made the change after the wiki was created because particles count & audio pitch have a giant benefit from being dynamic numbers instead of exact numbers. Otherwise you would have to copy/paste all possible values in. That's the reason math operations exist in the first place. More flexibility with less code.
